AUGMENTATION: True
IMAGE_SIZE: [224,224,3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.003

label_mapping:
  Normal : 0
  Cyst: 1
  Tumor: 2
  Stone: 3

data_loader:
  target_size: (224, 224)
  batch_size: 32
  color_mode: "grayscale"
  class_mode: "categorical"
  seed: 42
  rotation_range: 10
  width_shift_range: 0.1
  height_shift_range: 0.1
  shear_range: 0.1
  zoom_range: 0.1
  horizontal_flip: True
  fill_mode: "nearest"

training:
  early_stopping:
    patience: 20
    min_delta: 0.001
    #baseline: 0.99
    monitor: "val_accuracy"
    mode: "max"
    verbose: 1
    restore_best_weights: True

  reduce_lr:
    factor: 0.5
    patience: 3
    min_lr: 0.000001
    cooldown: 2
    min_delta: 0.001
    monitor: "val_loss"
    mode: "min"
    verbose: 1

  checkpoint:
    monitor: 'val_objective'
    mode: "max"
    filepath: "artifacts/optuna_best_model/best_model.keras"
    save_best_only: true
    verbose: 1
    save_freq: 'epoch'
    save_weights_only: false

Optuna_tuning:
  min_n_conv_layers: 3 #
  max_n_conv_layers: 6 #
  min_n_dense_layers: 2 #
  max_n_dense_layers: 5 #
  optimizer: ['adam', 'sgd'] #
  Conv2D_strides_size: ["1x1", "2x2"] #
  MaxPooling2D_strides_size: ["2x2"] #
  filters: [32,64,128,512]
  dense_units: [32,64,128,512]
  Conv2D_kernel_size: ["3x3"] #
  MaxPooling2D_kernel_size: ["2x2"] #
  activation: ['relu','softmax']
  loss: "categorical_crossentropy"  #
  metrics: ["accuracy"]  #
  epochs: 30  #