artifacts_roots : artifacts

data_ingestion:
  root_dir : artifacts/ data_ingestion
  source_URL : "https://drive.google.com/file/d/1zzMlKIMcinhAI8TsLq6CnABen3n0dCIV/view?usp=drive_link"
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion

make_data_csv:
  root_dir: artifacts/data_csv
  source_file_path: artifacts/data_ingestion/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone/CT-KIDNEY-DATASET-Normal-Cyst-Tumor-Stone
  base_csv_file: artifacts/data_csv/base.csv

data_split:
  root_dir: artifacts/data_split
  base_csv_path: artifacts/data_csv/base.csv
  train_csv_path: artifacts/data_split/train.csv
  val_csv_path: artifacts/data_split/val.csv
  test_csv_path: artifacts/data_split/test.csv
  test_size: 0.3
  random_state: 42

data_loader:
  root_dir: artifacts/data_split
  train_data: train.csv
  valid_data: val.csv
  test_data: test.csv

callbacks:
  checkpoint_dir: artifacts/checkpoints


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5


